name: posty
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  animated_text_kit: ^4.2.3
  gap: ^3.0.1
  get: ^4.7.2
  get_storage: ^2.1.1
  flutter_spinkit: ^5.2.1
  dio: ^5.8.0+1
  retrofit: ^4.6.0
  retrofit_generator: ^10.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  json_annotation: ^4.9.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  firebase_crashlytics: ^5.0.0
  firebase_analytics: ^12.0.0
  mockito: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
